version: '3'
services:

  scheduler:
    image: docker.pkg.github.com/hadar-simulator/community-server/scheduler:1
    environment:
      # ACCESS_TOKEN: 'password'
      INTERN_ORIGIN: scheduler:8000 # Some api should be only available by intern calls
      DATA_EXPIRATION_MS: 86400000 # 24h
      DATA_PATH: '/data'
    ports:
    - '8080:8080'
    volumes:
    - '/home/ubuntu/data:/data'

  worker:
    image: docker.pkg.github.com/hadar-simulator/community-server/worker:1-0.3.1
    environment:
      SCHEDULER_URL: http://scheduler:8080
