version: '3'
services:
  hadar:
    image: docker.pkg.github.com/hadar-simulator/community-server/server:0.3.1-3
    environment:
      # ACCESS_TOKEN: 'password'
      GARBAGE_LOOP_SEC: 30
      DB_PATH: '/data/db.sqlite3'
    ports:
    - '8080:8080'
    volumes:
    - '/home/ubuntu/data:/data'